name: Deploy IT-Recruitment Application

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}"
            export GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
            export MODEL_NAME="${{ vars.MODEL_NAME }}"

            cd /root/app/please-summarize

            git pull origin main

            docker stop discord-bot || true
            docker rm discord-bot || true

            docker build -t discord-summarizer-bot .

            docker run -d \
              --name discord-bot \
              -e DISCORD_TOKEN="$DISCORD_TOKEN" \
              -e GEMINI_API_KEY="$GEMINI_API_KEY" \
              -e MODEL_NAME="$MODEL_NAME" \
              -e TZ=Asia/Ho_Chi_Minh \
              --restart unless-stopped \
              discord-summarizer-bot
