name: Deploy IT-Recruitment Application

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/app/please-summarize

            git pull origin main

            docker stop discord-bot || true
            docker rm discord-bot || true

            docker build -t discord-summarizer-bot .

            docker run -d \
              --name discord-bot \
              --env-file .env \
              -v discord-bot-data:/data \
              -e TZ=Asia/Ho_Chi_Minh \
              --restart unless-stopped \
              discord-summarizer-bot
